/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BalanceGeneral;

/**
 *
 * @author GATUSSO
 */
public class SubEgresos extends javax.swing.JPanel {

    /**
     * Creates new form PedidoVer
     */
    public SubEgresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 520));
        setMinimumSize(new java.awt.Dimension(790, 520));
        setPreferredSize(new java.awt.Dimension(790, 520));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gasto.png"))); // NOI18N
        jLabel1.setText("EGRESOS");
        add(jLabel1);
        jLabel1.setBounds(70, 10, 120, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar 16.png"))); // NOI18N
        jLabel3.setText("Buscar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel3);
        jLabel3.setBounds(230, 60, 70, 40);
        add(jSeparator5);
        jSeparator5.setBounds(10, 20, 50, 20);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(10, 20, 10, 360);
        add(jSeparator1);
        jSeparator1.setBounds(190, 20, 480, 10);
        add(jSeparator2);
        jSeparator2.setBounds(10, 500, 760, 20);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4);
        jSeparator4.setBounds(770, 20, 10, 360);
        add(jSeparator6);
        jSeparator6.setBounds(60, 90, 160, 10);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/filtro.png"))); // NOI18N
        jLabel2.setText("Aplicar filtro");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel2);
        jLabel2.setBounds(520, 70, 100, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario1.png"))); // NOI18N
        jLabel6.setText("Desde");
        add(jLabel6);
        jLabel6.setBounds(340, 70, 80, 20);
        add(jSeparator7);
        jSeparator7.setBounds(340, 90, 80, 10);
        add(jSeparator8);
        jSeparator8.setBounds(430, 90, 80, 10);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario1.png"))); // NOI18N
        jLabel7.setText("Hasta");
        add(jLabel7);
        jLabel7.setBounds(430, 70, 80, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Código ", "Nombre", "Cantidad", "Precio (S/)"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 120, 570, 110);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Proveedor:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel4);
        jLabel4.setBounds(70, 310, 60, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Ingrese nombre del gasto");
        jTextField2.setBorder(null);
        add(jTextField2);
        jTextField2.setBounds(60, 70, 170, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setBorder(null);
        jTextField3.setEnabled(false);
        add(jTextField3);
        jTextField3.setBounds(140, 280, 150, 20);
        add(jSeparator9);
        jSeparator9.setBounds(140, 300, 140, 10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Gasto:");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel5);
        jLabel5.setBounds(70, 280, 40, 30);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Apuntes.jpg"))); // NOI18N
        jLabel15.setText("Detalles");
        add(jLabel15);
        jLabel15.setBounds(30, 250, 90, 30);

        jToggleButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModificarBtn1.png"))); // NOI18N
        jToggleButton1.setText("Modificar");
        jToggleButton1.setBorder(null);
        jToggleButton1.setContentAreaFilled(false);
        add(jToggleButton1);
        jToggleButton1.setBounds(420, 300, 83, 25);

        jToggleButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminarBtn1.png"))); // NOI18N
        jToggleButton3.setText("Eliminar");
        jToggleButton3.setBorder(null);
        jToggleButton3.setContentAreaFilled(false);
        add(jToggleButton3);
        jToggleButton3.setBounds(420, 330, 77, 25);

        jToggleButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadirbtn1.png"))); // NOI18N
        jToggleButton2.setText("Añadir");
        jToggleButton2.setBorder(null);
        jToggleButton2.setContentAreaFilled(false);
        add(jToggleButton2);
        jToggleButton2.setBounds(410, 270, 80, 25);
        add(jSeparator10);
        jSeparator10.setBounds(140, 330, 140, 10);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setBorder(null);
        jTextField4.setEnabled(false);
        add(jTextField4);
        jTextField4.setBounds(140, 310, 150, 20);

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator15);
        jSeparator15.setBounds(340, 250, 20, 110);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
