/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BalanceGeneral;

/**
 *
 * @author GATUSSO
 */
public class SubIngresos extends javax.swing.JPanel {

    /**
     * Creates new form PedidoNuevo
     */
    public SubIngresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        btnProveedores1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 520));
        setMinimumSize(new java.awt.Dimension(790, 520));
        setPreferredSize(new java.awt.Dimension(790, 520));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("INGRESOS DE EVP");
        add(jLabel1);
        jLabel1.setBounds(50, -9, 140, 40);

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText(" Busquedaa especifica...");
        jTextField2.setBorder(null);
        add(jTextField2);
        jTextField2.setBounds(80, 40, 140, 20);

        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("  Desde ...");
        jTextField3.setBorder(null);
        add(jTextField3);
        jTextField3.setBounds(270, 40, 80, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(250, 30, 30, 40);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel13.setText("Total de Ingresos:");
        add(jLabel13);
        jLabel13.setBounds(350, 180, 110, 20);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel14.setText("Codigo");
        add(jLabel14);
        jLabel14.setBounds(50, 210, 110, 40);

        jTextField9.setBorder(null);
        add(jTextField9);
        jTextField9.setBounds(100, 220, 130, 20);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setText("Ver Detalles");
        add(jLabel15);
        jLabel15.setBounds(40, 190, 140, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo Operacion", "Descripcion", "Hecho por", "Cantidad (S/.)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 600, 90);

        jTextField1.setBorder(null);
        add(jTextField1);
        jTextField1.setBounds(440, 280, 80, 20);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel16.setText("Total:");
        add(jLabel16);
        jLabel16.setBounds(400, 280, 40, 30);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        jLabel17.setText(" Imprimir");
        add(jLabel17);
        jLabel17.setBounds(530, 310, 160, 60);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf.png"))); // NOI18N
        jLabel18.setText(" Exportar");
        add(jLabel18);
        jLabel18.setBounds(410, 310, 160, 60);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        jLabel19.setText(" Eliminar Fila");
        add(jLabel19);
        jLabel19.setBounds(190, 290, 160, 40);
        add(jSeparator1);
        jSeparator1.setBounds(200, 10, 470, 10);
        add(jSeparator2);
        jSeparator2.setBounds(10, 380, 660, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(10, 10, 10, 370);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4);
        jSeparator4.setBounds(670, 10, 10, 370);
        add(jSeparator5);
        jSeparator5.setBounds(10, 10, 30, 20);
        add(jSeparator6);
        jSeparator6.setBounds(80, 60, 140, 10);
        add(jSeparator7);
        jSeparator7.setBounds(270, 60, 80, 10);
        add(jSeparator12);
        jSeparator12.setBounds(470, 200, 130, 10);
        add(jSeparator13);
        jSeparator13.setBounds(100, 240, 130, 10);
        add(jSeparator15);
        jSeparator15.setBounds(560, 270, 0, 2);
        add(jSeparator17);
        jSeparator17.setBounds(440, 300, 80, 10);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar 16.png"))); // NOI18N
        add(jLabel20);
        jLabel20.setBounds(40, 30, 30, 40);

        jTextField11.setForeground(new java.awt.Color(204, 204, 204));
        jTextField11.setText("  Antes ...");
        jTextField11.setBorder(null);
        add(jTextField11);
        jTextField11.setBounds(390, 40, 80, 20);
        add(jSeparator18);
        jSeparator18.setBounds(390, 60, 80, 10);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        add(jLabel21);
        jLabel21.setBounds(370, 30, 30, 40);

        btnProveedores1.setBackground(new java.awt.Color(245, 156, 26));
        btnProveedores1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnProveedores1.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores1.setText("Consultar");
        btnProveedores1.setBorder(null);
        btnProveedores1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores1.setFocusPainted(false);
        btnProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedores1ActionPerformed(evt);
            }
        });
        add(btnProveedores1);
        btnProveedores1.setBounds(490, 30, 80, 30);

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel22.setText("Detalle");
        add(jLabel22);
        jLabel22.setBounds(50, 240, 110, 40);

        jTextField12.setBorder(null);
        add(jTextField12);
        jTextField12.setBounds(100, 250, 240, 20);
        add(jSeparator19);
        jSeparator19.setBounds(100, 270, 240, 10);

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel23.setText("Tipo de Operacion:");
        add(jLabel23);
        jLabel23.setBounds(300, 210, 110, 40);
        add(jSeparator20);
        jSeparator20.setBounds(450, 270, 130, 10);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel24.setText("Realizado por:");
        add(jLabel24);
        jLabel24.setBounds(360, 240, 110, 40);

        jTextField14.setBorder(null);
        add(jTextField14);
        jTextField14.setBounds(450, 250, 130, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido", "Venta de Libro" }));
        add(jComboBox2);
        jComboBox2.setBounds(430, 220, 110, 20);

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anadir-punto-de-anclaje_1.png"))); // NOI18N
        jLabel25.setText("Modificar Datos");
        add(jLabel25);
        jLabel25.setBounds(30, 290, 160, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedores1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProveedores1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
