/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registro;

import BaseDatos.ConexionMySQL;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class SubInventario extends javax.swing.JPanel {

    /**
     * Creates new form SubInventario
     */
    public SubInventario() {
        initComponents();
        buscarInsumo();
        codInsumoText.setVisible(false);
        modificarButton.setVisible(false);     
        
    }
    
    public void desbloquear(){
        txtInsumo.setEnabled(true);
        txtStock.setEnabled(true);
        proveedorBox.setEnabled(true);
    }
    
    public void limpiar(){
        txtInsumo.setText(null);
        txtStock.setText(null);
        proveedorBox.setSelectedItem(null);
    }
    
     public void bloquear(){
        txtInsumo.setEnabled(false);
        txtStock.setEnabled(false);
        proveedorBox.setEnabled(false);
    }
    
    public void buscarInsumo(){
        String[] registro=new String[3];      
        String asql="";
        
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Insumo");
        modelo.addColumn("Stock");
        modelo.addColumn("Proveedor");
        tablaInventario.setModel(modelo);
        
        ConexionMySQL mysql=new ConexionMySQL(); 
        Connection cn=mysql.conectar();
        
        asql="SELECT * FROM inventario";
        
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(asql);
            
            while(rs.next())
            {
                registro[0]=rs.getString("insumo");
                registro[1]=rs.getString("stock");
                registro[2]=rs.getString("cod_proveedor");
                
                modelo.addRow(registro);
            }
            tablaInventario.setModel(modelo);
        }
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null,ex);
        }   
    }
    
    public void agregarInsumo(){
        ConexionMySQL  mysql=new ConexionMySQL();
        Connection cn=mysql.conectar();
        
        String insu,stock,prove;
        insu = txtInsumo.getText();
        stock = txtStock.getText();
        prove = proveedorBox.getSelectedItem().toString();   
               
        String asql="";
        String mensaje="";
        
        asql = "INSERT INTO inventario(insumo,stock,cod_proveedor) "+
                "VALUES(? ,? ,? )";
        
        mensaje="Los datos se han guardado de manera satisfactoria";
        try 
        {
            PreparedStatement pst = cn.prepareStatement(asql);
            pst.setString(1, insu);
            pst.setString(2, stock);
            pst.setString(3, prove);          
            
            int n=pst.executeUpdate();
            
            if(n>0)
            {            
                JOptionPane.showMessageDialog(null,mensaje,"Guardando",JOptionPane.INFORMATION_MESSAGE);
                buscarInsumo();
            }
            bloquear();
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtInsumo = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JToggleButton();
        btnModificar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        proveedorBox = new javax.swing.JComboBox<>();
        modificarButton = new javax.swing.JToggleButton();
        codInsumoText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 520));
        setMinimumSize(new java.awt.Dimension(790, 520));
        setPreferredSize(new java.awt.Dimension(790, 520));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario1.jpg"))); // NOI18N
        jLabel2.setText("INVENTARIO");
        add(jLabel2);
        jLabel2.setBounds(50, 0, 190, 48);
        add(jSeparator1);
        jSeparator1.setBounds(50, 210, 660, 10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Proveedor:");
        add(jLabel5);
        jLabel5.setBounds(100, 380, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boxes.jpg"))); // NOI18N
        jLabel6.setText("Detalles");
        add(jLabel6);
        jLabel6.setBounds(70, 250, 120, 32);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Stock:");
        add(jLabel7);
        jLabel7.setBounds(100, 340, 60, 20);

        txtInsumo.setEnabled(false);
        add(txtInsumo);
        txtInsumo.setBounds(180, 300, 170, 20);

        txtStock.setEnabled(false);
        add(txtStock);
        txtStock.setBounds(180, 340, 40, 20);

        btnAñadir.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadirbtn1.png"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.setBorder(null);
        btnAñadir.setBorderPainted(false);
        btnAñadir.setContentAreaFilled(false);
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadir.setFocusPainted(false);
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        add(btnAñadir);
        btnAñadir.setBounds(490, 280, 100, 30);

        btnModificar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModificarBtn1.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar);
        btnModificar.setBounds(500, 330, 100, 30);

        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminarBtn1.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(490, 380, 110, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Insumo:");
        add(jLabel8);
        jLabel8.setBounds(100, 300, 60, 20);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2);
        jSeparator2.setBounds(420, 240, 10, 230);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Insumo", "Stock", "Proveedor"
            }
        ));
        jScrollPane2.setViewportView(tablaInventario);

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 70, 570, 110);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setEnabled(false);
        btnGuardar.setPreferredSize(new java.awt.Dimension(65, 23));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(170, 440, 110, 23);

        ConexionMySQL mysql=new ConexionMySQL();
        Connection cn=mysql.conectar();
        String asql2="SELECT * FROM proveedor";
        try
        {
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(asql2);

            while(rs.next())
            {
                proveedorBox.addItem(rs.getString("razon_social"));

            }
            proveedorBox.setSelectedItem(null);
            proveedorBox.setEnabled(false);
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
        add(proveedorBox);
        proveedorBox.setBounds(180, 380, 180, 20);

        modificarButton.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        modificarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarbutton.png"))); // NOI18N
        modificarButton.setText("Modificar");
        modificarButton.setBorder(null);
        modificarButton.setContentAreaFilled(false);
        modificarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarButton.setEnabled(false);
        modificarButton.setFocusPainted(false);
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });
        add(modificarButton);
        modificarButton.setBounds(180, 440, 100, 30);

        codInsumoText.setEditable(false);
        codInsumoText.setEnabled(false);
        add(codInsumoText);
        codInsumoText.setBounds(660, 160, 70, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        desbloquear();
        limpiar();
        btnGuardar.setEnabled(true);
        btnGuardar.setVisible(true);
        modificarButton.setVisible(false);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            agregarInsumo();
            limpiar();
            buscarInsumo();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Complete todos los espacios");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
//        actualizar();
         try {
            ConexionMySQL  mysql=new ConexionMySQL();
            Connection cn=mysql.conectar();

            String ins, stock, prov;
            
            ins=txtInsumo.getText();
            stock= txtStock.getText();
            prov = proveedorBox.getSelectedItem().toString();

            String asql="";
            String mensaje="";
            String codInsumo= codInsumoText.getText();
            
            mensaje="Los datos han sido modificados de manera satisfactoria";
            String sql="UPDATE inventario SET "
                 + "insumo = '"+ins+"',"
                 + "stock = '"+stock+"',"
                 + "cod_proveedor = '"+prov+"'"
                 + " WHERE num_insumo = '"+codInsumo+"'"; 
            
            PreparedStatement pst = cn.prepareStatement(sql);
            int n= pst.executeUpdate();
            if(n>0)
            {            
                JOptionPane.showMessageDialog(null,mensaje,"Actualizar",JOptionPane.INFORMATION_MESSAGE);
                buscarInsumo();
            limpiar();
            bloquear();
            }
            
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        int fila = tablaInventario.getSelectedRow();
         

        if(fila>=0)
        {
            desbloquear();
            proveedorBox.setVisible(true);
            String ins = tablaInventario.getValueAt(fila, 0).toString();
                       
           
            ConexionMySQL mysql=new ConexionMySQL();       
            Connection cn=mysql.conectar();
            String asql="";
            asql="SELECT * FROM inventario "
                    +"WHERE CONCAT(insumo) LIKE '%"+ins+"%'";
        
            try 
            {
                Statement st=cn.createStatement();
                ResultSet rs=st.executeQuery(asql);

                while(rs.next())
                {
                    codInsumoText.setText(rs.getString("num_insumo"));
                    txtInsumo.setText(rs.getString("insumo"));
                    txtStock.setText(rs.getString("stock"));
                    proveedorBox.setSelectedItem(rs.getString("cod_proveedor"));
                    
                }
                
            }
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(null,ex);
            }
            
                       
            btnGuardar.setVisible(false);
            modificarButton.setVisible(true);
            modificarButton.setEnabled(true);
                        
            
        }else{
            JOptionPane.showMessageDialog(null, "Elija un insumo de la tabla", "Error", JOptionPane.ERROR_MESSAGE);   
        }

       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaInventario.getSelectedRow();
         

        if(fila>=0)
        {
            int resp = JOptionPane.showConfirmDialog(null, "¿Seguro que quiere borrar el registro del insumo?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE );
            if(resp==0){
            
            String ins = tablaInventario.getValueAt(fila, 0).toString();
            
            ConexionMySQL mysql=new ConexionMySQL();       
            Connection cn=mysql.conectar();
            String instSql="DELETE FROM inventario "
                    +"WHERE CONCAT(insumo) LIKE '%"+ins+"%'";
        
            try 
            {
                PreparedStatement pst = cn.prepareStatement(instSql);
                pst.execute();
                buscarInsumo();
                JOptionPane.showMessageDialog(null, "Elemento eliminado con éxito");


            }
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(null,ex);
            }
            }

        }
        else
        {
    JOptionPane.showMessageDialog(null, "Elija un insumo de la tabla", "Error", JOptionPane.ERROR_MESSAGE);   
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAñadir;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JToggleButton btnModificar;
    private javax.swing.JTextField codInsumoText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton modificarButton;
    private javax.swing.JComboBox<String> proveedorBox;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtInsumo;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
